name: Daily NESCO Balance Check (Single)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'   # 10:00 AM BST (daily)
    - cron: '0 8 * * *'   # 2:00 PM BST (low balance check)
    - cron: '0 14 * * *'  # 8:00 PM BST (low balance check)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CUST_NO: ${{ secrets.CUST_NO }}
        run: python nesco_single.py
