name: NESCO Multi-Meter Balance Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-telegram-bot

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CUST_LIST: ${{ secrets.CUST_LIST }}  # Comma-separated list
        run: python script.py
